services:
  - type: web
    name: breastcancer-ppd-api
    env: python
    region: singapore
    plan: free
    rootDir: Api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:8000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
